### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [XDRAGON2002/PORTFOLIO#1]
Hey its me,
I visited the website of your portfolio and its awesome!!

I would like to update the README.md file for this repository if its ok?

**Comment by XDRAGON2002** [comment]
Hi Atharva!

Great to see you.

But since this is a personal portfolio website, I'd rather not accept PRs as it's not supposed to be opensource. Thanks for the offer though!

**Comment by the-amazing-atharva** [comment]
Yeah no worries!

Thanks for the reply

Do let me know if you need someone to contribute to README.md for any of your projects
